# Generated by Django 5.0.2 on 2024-05-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='status',
        ),
    ]
