# Generated by Django 5.0.2 on 2024-05-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_razorpaypayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
