# Generated by Django 5.0.2 on 2024-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_razorpaypayment_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='payment_id',
            field=models.CharField(default=1, max_length=36, verbose_name='Payment ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='razorpaypayment',
            name='signature_id',
            field=models.CharField(default=1, max_length=128, verbose_name='Signature ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='razorpaypayment',
            name='status',
            field=models.CharField(default='Pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
