# Generated by Django 5.0.2 on 2024-05-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0002_alter_show_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='greet.movie'),
            preserve_default=False,
        ),
    ]
