# Generated by Django 5.0.2 on 2024-05-08 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0003_alter_show_movie'),
        ('payments', '0002_remove_razorpaypayment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='greet.booking')),
                ('razorpay_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='payments.razorpaypayment')),
            ],
        ),
    ]
