# Generated by Django 5.0.2 on 2024-05-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0004_bookingpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingPayment',
        ),
    ]
