# Generated by Django 5.0.2 on 2024-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0006_alter_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.TimeField(choices=[('11:30', '11:30 AM'), ('14:30', '2:30 PM'), ('17:00', '5:00 PM'), ('21:00', '9:00 PM')]),
        ),
    ]
