# Generated by Django 5.0.2 on 2024-05-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0007_alter_booking_payment_status_alter_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
