# Generated by Django 5.0.2 on 2024-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0008_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.TimeField(),
        ),
    ]
