# Generated by Django 5.0.2 on 2024-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greet', '0011_show_language_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
